<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.0000" tests="1" failures="1">
  <testsuite name="" timestamp="2021-11-03T14:21:00" tests="0" file="cypress/integration/block-basics.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Root Suite.Blocks Tests" timestamp="2021-11-03T14:21:00" tests="1" time="0.0000" failures="1">
    <testcase name="&quot;before each&quot; hook: setupBeforeEach for &quot;Add Block: Empty&quot;" time="0.0000" classname="Blocks Tests">
      <failure message="`cy.request()` failed on:

http://localhost:8080/Plone/

The response we received from your web server was:

  &gt; 400: Bad Request

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: http://localhost:8080/Plone/
Headers: {
  &quot;Connection&quot;: &quot;keep-alive&quot;,
  &quot;user-agent&quot;: &quot;Mozilla/5.0 (Macintosh; Intel Mac OS X 11_6_0) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/7.3.0 Chrome/89.0.4328.0 Electron/12.0.0-beta.14 Safari/537.36&quot;,
  &quot;accept&quot;: &quot;application/json&quot;,
  &quot;cookie&quot;: &quot;auth_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYzNTk5MjQ2MCwiZnVsbG5hbWUiOm51bGx9.C-88cMkyDFRaM7MyuBnvW6U7u6FdVOWk4br1L6XdHjE; __ac=\&quot;NjE2NDZkNjk2ZTo%253D\&quot;&quot;,
  &quot;authorization&quot;: &quot;Basic YWRtaW46YWRtaW4=&quot;,
  &quot;accept-encoding&quot;: &quot;gzip, deflate&quot;,
  &quot;content-type&quot;: &quot;application/json&quot;,
  &quot;content-length&quot;: 306
}
Body: {&quot;@type&quot;:&quot;Folder&quot;,&quot;id&quot;:&quot;cypress&quot;,&quot;title&quot;:&quot;Cypress&quot;,&quot;blocks&quot;:{&quot;d3f1c443-583f-4e8e-a682-3bf25752a300&quot;:{&quot;@type&quot;:&quot;title&quot;},&quot;7624cf59-05d0-4055-8f55-5fd6597d84b0&quot;:{&quot;@type&quot;:&quot;text&quot;}},&quot;blocks_layout&quot;:{&quot;items&quot;:[&quot;d3f1c443-583f-4e8e-a682-3bf25752a300&quot;,&quot;7624cf59-05d0-4055-8f55-5fd6597d84b0&quot;]},&quot;allow_discussion&quot;:false}

-----------------------------------------------------------

The response we got was:

Status: 400 - Bad Request
Headers: {
  &quot;content-length&quot;: &quot;2197&quot;,
  &quot;content-type&quot;: &quot;application/json&quot;,
  &quot;date&quot;: &quot;Wed, 03 Nov 2021 14:21:01 GMT&quot;,
  &quot;server&quot;: &quot;waitress&quot;,
  &quot;via&quot;: &quot;waitress&quot;,
  &quot;x-frame-options&quot;: &quot;SAMEORIGIN&quot;,
  &quot;x-powered-by&quot;: &quot;Zope (www.zope.org), Python (www.python.org)&quot;
}
Body: {
  &quot;message&quot;: &quot;The id \&quot;cypress\&quot; is invalid - it is already in use.&quot;,
  &quot;traceback&quot;: [
    &quot;File \&quot;/plone/buildout-cache/eggs/cp38/Zope-4.5.5-py3.8.egg/ZPublisher/WSGIPublisher.py\&quot;, line 162, in transaction_pubevents&quot;,
    &quot;    yield&quot;,
    &quot;&quot;,
    &quot;  File \&quot;/plone/buildout-cache/eggs/cp38/Zope-4.5.5-py3.8.egg/ZPublisher/WSGIPublisher.py\&quot;, line 371, in publish_module&quot;,
    &quot;    response = _publish(request, new_mod_info)&quot;,
    &quot;&quot;,
    &quot;  File \&quot;/plone/buildout-cache/eggs/cp38/Zope-4.5.5-py3.8.egg/ZPublisher/WSGIPublisher.py\&quot;, line 266, in publish&quot;,
    &quot;    result = mapply(obj,&quot;,
    &quot;&quot;,
    &quot;  File \&quot;/plone/buildout-cache/eggs/cp38/Zope-4.5.5-py3.8.egg/ZPublisher/mapply.py\&quot;, line 85, in mapply&quot;,
    &quot;    return debug(object, args, context)&quot;,
    &quot;&quot;,
    &quot;  File \&quot;/plone/buildout-cache/eggs/cp38/Zope-4.5.5-py3.8.egg/ZPublisher/WSGIPublisher.py\&quot;, line 63, in call_object&quot;,
    &quot;    return obj(*args)&quot;,
    &quot;&quot;,
    &quot;  File \&quot;/plone/buildout-cache/eggs/cp38/plone.rest-1.6.2-py3.8.egg/plone/rest/service.py\&quot;, line 22, in __call__&quot;,
    &quot;    return self.render()&quot;,
    &quot;&quot;,
    &quot;  File \&quot;/plone/buildout-cache/eggs/cp38/plone.restapi-8.9.1-py3.8.egg/plone/restapi/services/__init__.py\&quot;, line 19, in render&quot;,
    &quot;    content = self.reply()&quot;,
    &quot;&quot;,
    &quot;  File \&quot;/plone/buildout-cache/eggs/cp38/plone.restapi-8.9.1-py3.8.egg/plone/restapi/services/content/add.py\&quot;, line 93, in reply&quot;,
    &quot;    obj = add(self.context, obj, rename=not bool(id_))&quot;,
    &quot;&quot;,
    &quot;  File \&quot;/plone/buildout-cache/eggs/cp38/plone.restapi-8.9.1-py3.8.egg/plone/restapi/services/content/utils.py\&quot;, line 89, in add&quot;,
    &quot;    new_id = container._setObject(id_, obj)&quot;,
    &quot;&quot;,
    &quot;  File \&quot;/plone/buildout-cache/eggs/cp38/Zope-4.5.5-py3.8.egg/OFS/ObjectManager.py\&quot;, line 350, in _setObject&quot;,
    &quot;    v = self._checkId(id)&quot;,
    &quot;&quot;,
    &quot;  File \&quot;/plone/buildout-cache/eggs/cp38/Products.CMFCore-2.5.0-py3.8.egg/Products/CMFCore/Skinnable.py\&quot;, line 196, in _checkId&quot;,
    &quot;    return superCheckId(self, id, allow_dup)&quot;,
    &quot;&quot;,
    &quot;  File \&quot;/plone/buildout-cache/eggs/cp38/Zope-4.5.5-py3.8.egg/OFS/ObjectManager.py\&quot;, line 141, in checkValidId&quot;,
    &quot;    raise BadRequest(&quot;
  ],
  &quot;type&quot;: &quot;BadRequest&quot;
}


https://on.cypress.io/request

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Blocks Tests`" type="CypressError"><![CDATA[CypressError: `cy.request()` failed on:

http://localhost:8080/Plone/

The response we received from your web server was:

  > 400: Bad Request

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: http://localhost:8080/Plone/
Headers: {
  "Connection": "keep-alive",
  "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_6_0) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/7.3.0 Chrome/89.0.4328.0 Electron/12.0.0-beta.14 Safari/537.36",
  "accept": "application/json",
  "cookie": "auth_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYzNTk5MjQ2MCwiZnVsbG5hbWUiOm51bGx9.C-88cMkyDFRaM7MyuBnvW6U7u6FdVOWk4br1L6XdHjE; __ac=\"NjE2NDZkNjk2ZTo%253D\"",
  "authorization": "Basic YWRtaW46YWRtaW4=",
  "accept-encoding": "gzip, deflate",
  "content-type": "application/json",
  "content-length": 306
}
Body: {"@type":"Folder","id":"cypress","title":"Cypress","blocks":{"d3f1c443-583f-4e8e-a682-3bf25752a300":{"@type":"title"},"7624cf59-05d0-4055-8f55-5fd6597d84b0":{"@type":"text"}},"blocks_layout":{"items":["d3f1c443-583f-4e8e-a682-3bf25752a300","7624cf59-05d0-4055-8f55-5fd6597d84b0"]},"allow_discussion":false}

-----------------------------------------------------------

The response we got was:

Status: 400 - Bad Request
Headers: {
  "content-length": "2197",
  "content-type": "application/json",
  "date": "Wed, 03 Nov 2021 14:21:01 GMT",
  "server": "waitress",
  "via": "waitress",
  "x-frame-options": "SAMEORIGIN",
  "x-powered-by": "Zope (www.zope.org), Python (www.python.org)"
}
Body: {
  "message": "The id \"cypress\" is invalid - it is already in use.",
  "traceback": [
    "File \"/plone/buildout-cache/eggs/cp38/Zope-4.5.5-py3.8.egg/ZPublisher/WSGIPublisher.py\", line 162, in transaction_pubevents",
    "    yield",
    "",
    "  File \"/plone/buildout-cache/eggs/cp38/Zope-4.5.5-py3.8.egg/ZPublisher/WSGIPublisher.py\", line 371, in publish_module",
    "    response = _publish(request, new_mod_info)",
    "",
    "  File \"/plone/buildout-cache/eggs/cp38/Zope-4.5.5-py3.8.egg/ZPublisher/WSGIPublisher.py\", line 266, in publish",
    "    result = mapply(obj,",
    "",
    "  File \"/plone/buildout-cache/eggs/cp38/Zope-4.5.5-py3.8.egg/ZPublisher/mapply.py\", line 85, in mapply",
    "    return debug(object, args, context)",
    "",
    "  File \"/plone/buildout-cache/eggs/cp38/Zope-4.5.5-py3.8.egg/ZPublisher/WSGIPublisher.py\", line 63, in call_object",
    "    return obj(*args)",
    "",
    "  File \"/plone/buildout-cache/eggs/cp38/plone.rest-1.6.2-py3.8.egg/plone/rest/service.py\", line 22, in __call__",
    "    return self.render()",
    "",
    "  File \"/plone/buildout-cache/eggs/cp38/plone.restapi-8.9.1-py3.8.egg/plone/restapi/services/__init__.py\", line 19, in render",
    "    content = self.reply()",
    "",
    "  File \"/plone/buildout-cache/eggs/cp38/plone.restapi-8.9.1-py3.8.egg/plone/restapi/services/content/add.py\", line 93, in reply",
    "    obj = add(self.context, obj, rename=not bool(id_))",
    "",
    "  File \"/plone/buildout-cache/eggs/cp38/plone.restapi-8.9.1-py3.8.egg/plone/restapi/services/content/utils.py\", line 89, in add",
    "    new_id = container._setObject(id_, obj)",
    "",
    "  File \"/plone/buildout-cache/eggs/cp38/Zope-4.5.5-py3.8.egg/OFS/ObjectManager.py\", line 350, in _setObject",
    "    v = self._checkId(id)",
    "",
    "  File \"/plone/buildout-cache/eggs/cp38/Products.CMFCore-2.5.0-py3.8.egg/Products/CMFCore/Skinnable.py\", line 196, in _checkId",
    "    return superCheckId(self, id, allow_dup)",
    "",
    "  File \"/plone/buildout-cache/eggs/cp38/Zope-4.5.5-py3.8.egg/OFS/ObjectManager.py\", line 141, in checkValidId",
    "    raise BadRequest("
  ],
  "type": "BadRequest"
}


https://on.cypress.io/request

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Blocks Tests`
    at http://localhost:3000/__cypress/runner/cypress_runner.js:140051:21
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:10791:23)
    at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:8726:31)
    at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:8783:18)
    at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:8828:10)
    at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:8908:18)
    at _drainQueueStep (http://localhost:3000/__cypress/runner/cypress_runner.js:5498:12)
    at _drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:5491:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:5507:5)
    at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:5377:14)
From Your Spec Code:
    at Context.eval (http://localhost:3000/__cypress/tests?p=cypress/integration/block-basics.js:415:15)]]></failure>
    </testcase>
  </testsuite>
</testsuites>